apiVersion: batch/v1
kind: Job
metadata:
  name: tikv-loaditem-job
  namespace: tidb-cluster
spec:
  template:
    spec:
      containers:
      - name: tikv-loaditem-job
        image: aliuchangjie/recommendation-tikv-loaditem
        imagePullPolicy: IfNotPresent
        ports:
        - name: tidb-cluster-pd
          containerPort: 2379
      restartPolicy: Never
  backoffLimit: 4